name = "SolarDynamo"
uuid = "b77104d9-93ed-49fd-acfd-b9fe0cfcdc18"
authors = ["Simone Ulzega", "Andreas Scheidegger"]
version = "1.0.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StochasticDelayDiffEq = "29a0d76e-afc8-11e9-03a4-eda52ae4b960"

[compat]
SpecialFunctions = "2.4.0"
StaticArrays = "1.9.8"
StochasticDelayDiffEq = "1.8.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
